# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-07 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20171204_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='arl',
            field=models.CharField(default='nombre de arl', max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cargo_aspirado',
            field=models.CharField(default='cargo al que aspira', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AddField(
            model_name='paciente',
            name='eps',
            field=models.CharField(default='nombre de la eps', max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], default='sexo', max_length=15),
        ),
    ]
