# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-07 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_auto_20181007_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_nacimiento',
        ),
    ]
