# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('union libre', 'Union libre'), ('viudo', 'Viudo/a'), ('divorciado', 'Divorciado/a'), ('comprometido', 'Comprometido/a')], max_length=50),
        ),
    ]
