# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiasClinicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizacion',
            name='motivo_consulta',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='actualizacion',
            name='tratamiento',
            field=models.TextField(default=None),
        ),
    ]
