# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiasClinicas', '0002_auto_20171201_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizacion',
            name='motivo_consulta',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='actualizacion',
            name='tratamiento',
            field=models.TextField(),
        ),
    ]
