# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-11 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('empresa', models.CharField(max_length=100)),
                ('cargo_aspirado', models.CharField(max_length=150)),
                ('eps', models.CharField(max_length=100)),
                ('arl', models.CharField(max_length=100)),
                ('examen_actual', models.CharField(choices=[('Pre-ingreso', 'preingreso'), ('Periodico', 'periodico'), ('Egreso', 'egreso'), ('Cambio labor', 'cambio labor'), ('Reincorporacion laboral', 'reincorporacion'), ('Rev. Paraclinicos', 'rev paraclinicos')], max_length=50)),
                ('ante_personales', models.CharField(max_length=1000)),
                ('ante_laborales', models.CharField(max_length=1000)),
                ('ante_familiares', models.CharField(max_length=1000)),
                ('ante_ginecobstre', models.CharField(max_length=1000)),
                ('ta', models.CharField(max_length=15)),
                ('fc', models.CharField(max_length=15)),
                ('fr', models.CharField(max_length=15)),
                ('peso', models.CharField(max_length=15)),
                ('talla', models.CharField(max_length=15)),
                ('imc', models.CharField(max_length=15)),
                ('cabeza_cuello', models.CharField(max_length=500)),
                ('sentidos', models.CharField(max_length=500)),
                ('cardiopulmonar', models.CharField(max_length=500)),
                ('abdomen', models.CharField(max_length=500)),
                ('osteomuscular', models.CharField(max_length=500)),
                ('neurologico', models.CharField(max_length=500)),
                ('esfera_mental', models.CharField(max_length=500)),
                ('apto_sin_pato', models.CharField(max_length=2)),
                ('apto_con_pato', models.CharField(max_length=2)),
                ('apto_con_restri', models.CharField(max_length=2)),
                ('aplazado', models.CharField(max_length=2)),
                ('apto_continuar_labor', models.CharField(max_length=2)),
                ('examen_retiro', models.CharField(max_length=2)),
                ('apto_alturas', models.CharField(max_length=2)),
                ('secuela_accidente_trabajo', models.CharField(choices=[('Si', 'si'), ('No', 'no')], max_length=2)),
                ('enfermedad_profesional', models.CharField(choices=[('Si', 'si'), ('No', 'no')], max_length=2)),
                ('efermedad_relTrabajo', models.CharField(choices=[('Si', 'si'), ('No', 'no')], max_length=2)),
                ('resultados_laboratorio', models.CharField(max_length=5000)),
                ('no_encuentra', models.CharField(max_length=2)),
                ('transitorias', models.CharField(max_length=2)),
                ('tiempo', models.CharField(max_length=10)),
                ('permanentes', models.CharField(max_length=2)),
                ('remite_eps', models.CharField(max_length=2)),
                ('continuar_eps', models.CharField(max_length=2)),
                ('remite_arl', models.CharField(max_length=2)),
                ('otras', models.CharField(max_length=500)),
                ('auditivo', models.CharField(max_length=2)),
                ('visual', models.CharField(max_length=2)),
                ('respiratorio', models.CharField(max_length=2)),
                ('biologico', models.CharField(max_length=2)),
                ('quimico', models.CharField(max_length=2)),
                ('ergonomico', models.CharField(max_length=2)),
                ('psicosocial', models.CharField(max_length=2)),
                ('accidente_trabajo', models.CharField(max_length=2)),
                ('otro', models.CharField(max_length=2)),
                ('ninguno', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Cabecera',
            fields=[
                ('numero_historia', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente')),
            ],
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='cabecera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historiasClinicas.Cabecera'),
        ),
    ]
