# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-07 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiasClinicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizacion',
            name='arl',
            field=models.CharField(default='nombre de arl', max_length=50),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='cambio_labor',
            field=models.CharField(choices=[('Si', 'si'), ('No', 'no')], default='no', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='cargo_aspirado',
            field=models.CharField(default='cargo al que aspira', max_length=100),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='egreso',
            field=models.CharField(choices=[('Si', 'si'), ('No', 'no')], default='no', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='empresa',
            field=models.CharField(default='empresa', max_length=100),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='eps',
            field=models.CharField(default='nombre de la eps', max_length=50),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='periodico',
            field=models.CharField(choices=[('Si', 'si'), ('No', 'no')], default='no', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='preingreso',
            field=models.CharField(choices=[('Si', 'si'), ('No', 'no')], default='no', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='reincorp_labor',
            field=models.CharField(choices=[('Si', 'si'), ('No', 'no')], default='no', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='rev_paraclinicos',
            field=models.CharField(choices=[('Si', 'si'), ('No', 'no')], default='no', max_length=2),
        ),
    ]
