# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-09 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiasClinicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizacion',
            name='motivo_consulta',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='tratamiento',
            field=models.TextField(default=None),
        ),
    ]
