# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-08 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiasClinicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizacion',
            name='fecha_at',
            field=models.DateField(null=True, verbose_name='Fecha accidente de trabajo'),
        ),
        migrations.AlterField(
            model_name='actualizacion',
            name='fecha_dxco',
            field=models.DateField(null=True, verbose_name='Fecha del diagnostico'),
        ),
    ]
