# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-07 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiasClinicas', '0002_auto_20181007_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizacion',
            name='ante_familiares',
            field=models.CharField(default='Antecedentes familiares', max_length=1000),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='ante_ginecobstre',
            field=models.CharField(default='Antecedentes ginecobstetricos', max_length=1000),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='ante_laborales',
            field=models.CharField(default='Antecedentes laborales', max_length=1000),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='ante_personales',
            field=models.CharField(default='Antecedentes personales', max_length=1000),
        ),
    ]
