# Generated by Django 2.1.4 on 2019-04-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiasClinicas', '0002_auto_20190416_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizacion',
            name='examen_actual',
            field=models.CharField(choices=[('Pre-ingreso', 'Pre-ingreso'), ('Periodico', 'Periodico'), ('Egreso', 'Egreso'), ('Cambio labor', 'Cambio labor'), ('Reincorporacion laboral', 'Reincorporacion laboral'), ('Rev. Paraclinicos', 'Rev. Paraclinicos'), ('Manipulacion de alimentos', 'Manipulacion de alimentos')], max_length=50, verbose_name='Examen'),
        ),
    ]
