# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-07 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiasClinicas', '0003_auto_20181007_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualizacion',
            name='motivo_consulta',
        ),
        migrations.RemoveField(
            model_name='actualizacion',
            name='tratamiento',
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='abdomen',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='cabeza_cuello',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='cardiopulmonar',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='esfera_mental',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='fc',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='fr',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='imc',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='neurologico',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='osteomuscular',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='peso',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='sentidos',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='ta',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='talla',
            field=models.CharField(default='', max_length=15),
        ),
    ]
