# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-07 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiasClinicas', '0004_auto_20181007_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizacion',
            name='aplazado',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='apto_alturas',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='apto_con_pato',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='apto_con_restri',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='apto_continuar_labor',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='apto_sin_pato',
            field=models.CharField(default='x', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='efermedad_relTrabajo',
            field=models.CharField(choices=[('Si', 'si'), ('No', 'no')], default='No', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='enfermedad_profesional',
            field=models.CharField(choices=[('Si', 'si'), ('No', 'no')], default='No', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='examen_retiro',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='fecha_at',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='fecha_dxco',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='secuela_accidente_trabajo',
            field=models.CharField(choices=[('Si', 'si'), ('No', 'no')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='actualizacion',
            name='cambio_labor',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='actualizacion',
            name='egreso',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='actualizacion',
            name='periodico',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='actualizacion',
            name='preingreso',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='actualizacion',
            name='reincorp_labor',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='actualizacion',
            name='rev_paraclinicos',
            field=models.CharField(default='', max_length=1),
        ),
    ]
