# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-07 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiasClinicas', '0005_auto_20181007_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizacion',
            name='accidente_trabajo',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='auditivo',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='biologico',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='continuar_eps',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='ergonomico',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='ninguno',
            field=models.CharField(default='x', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='no_encuentra',
            field=models.CharField(default='x', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='otras',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='otro',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='permanentes',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='psicosocial',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='quimico',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='remite_arl',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='remite_eps',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='respiratorio',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='resultados_laboratorio',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='tiempo',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='transitorias',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='visual',
            field=models.CharField(default='', max_length=2),
        ),
    ]
