# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-07 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiasClinicas', '0006_auto_20181007_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizacion',
            name='fecha_at',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='actualizacion',
            name='fecha_dxco',
            field=models.DateField(default=None),
        ),
    ]
