# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-07 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historiasClinicas', '0007_auto_20181007_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualizacion',
            name='fecha_at',
        ),
        migrations.RemoveField(
            model_name='actualizacion',
            name='fecha_dxco',
        ),
    ]
